// Auto-generated by scripts/download-screenshots.mjs. Do not edit.
export const LOCAL_SCREENSHOT_MAP: Record<string, string[]> = {
  "com.istack.sweet_camera": [
    "/app-screenshots/com.istack.sweet_camera/1.jpg",
    "/app-screenshots/com.istack.sweet_camera/2.jpg",
    "/app-screenshots/com.istack.sweet_camera/3.jpg",
    "/app-screenshots/com.istack.sweet_camera/4.jpg"
  ],
  "com.istack.photo_collage": [
    "/app-screenshots/com.istack.photo_collage/1.jpg",
    "/app-screenshots/com.istack.photo_collage/2.jpg",
    "/app-screenshots/com.istack.photo_collage/3.jpg",
    "/app-screenshots/com.istack.photo_collage/4.jpg"
  ],
  "com.istack.time_warp_scan": [
    "/app-screenshots/com.istack.time_warp_scan/1.jpg",
    "/app-screenshots/com.istack.time_warp_scan/2.jpg",
    "/app-screenshots/com.istack.time_warp_scan/3.jpg",
    "/app-screenshots/com.istack.time_warp_scan/4.jpg",
    "/app-screenshots/com.istack.time_warp_scan/5.jpg"
  ],
  "com.istack.photo_lock": [
    "/app-screenshots/com.istack.photo_lock/1.jpg",
    "/app-screenshots/com.istack.photo_lock/2.jpg",
    "/app-screenshots/com.istack.photo_lock/3.jpg",
    "/app-screenshots/com.istack.photo_lock/4.jpg",
    "/app-screenshots/com.istack.photo_lock/5.jpg"
  ],
  "com.istack.gps.photo": [
    "/app-screenshots/com.istack.gps.photo/1.png",
    "/app-screenshots/com.istack.gps.photo/2.jpg",
    "/app-screenshots/com.istack.gps.photo/3.jpg",
    "/app-screenshots/com.istack.gps.photo/4.jpg",
    "/app-screenshots/com.istack.gps.photo/5.jpg",
    "/app-screenshots/com.istack.gps.photo/6.jpg"
  ],
  "com.istack.cut_and_paste_photos": [
    "/app-screenshots/com.istack.cut_and_paste_photos/1.jpg",
    "/app-screenshots/com.istack.cut_and_paste_photos/2.jpg",
    "/app-screenshots/com.istack.cut_and_paste_photos/3.jpg",
    "/app-screenshots/com.istack.cut_and_paste_photos/4.jpg",
    "/app-screenshots/com.istack.cut_and_paste_photos/5.jpg"
  ],
  "com.istack.sticker_maker": [
    "/app-screenshots/com.istack.sticker_maker/1.jpg",
    "/app-screenshots/com.istack.sticker_maker/2.jpg",
    "/app-screenshots/com.istack.sticker_maker/3.jpg",
    "/app-screenshots/com.istack.sticker_maker/4.jpg"
  ],
  "com.istack.word.reader": [
    "/app-screenshots/com.istack.word.reader/1.jpg",
    "/app-screenshots/com.istack.word.reader/2.jpg",
    "/app-screenshots/com.istack.word.reader/3.jpg",
    "/app-screenshots/com.istack.word.reader/4.jpg",
    "/app-screenshots/com.istack.word.reader/5.jpg",
    "/app-screenshots/com.istack.word.reader/6.jpg"
  ],
  "com.istack.office.reader": [
    "/app-screenshots/com.istack.office.reader/1.jpg",
    "/app-screenshots/com.istack.office.reader/2.jpg",
    "/app-screenshots/com.istack.office.reader/3.jpg",
    "/app-screenshots/com.istack.office.reader/4.jpg",
    "/app-screenshots/com.istack.office.reader/5.jpg",
    "/app-screenshots/com.istack.office.reader/6.jpg"
  ],
  "com.istack.img2.pdf": [
    "/app-screenshots/com.istack.img2.pdf/1.jpg",
    "/app-screenshots/com.istack.img2.pdf/2.jpg",
    "/app-screenshots/com.istack.img2.pdf/3.jpg",
    "/app-screenshots/com.istack.img2.pdf/4.jpg",
    "/app-screenshots/com.istack.img2.pdf/5.jpg"
  ],
  "com.istack.sigature.app": [
    "/app-screenshots/com.istack.sigature.app/1.jpg",
    "/app-screenshots/com.istack.sigature.app/2.jpg",
    "/app-screenshots/com.istack.sigature.app/3.jpg",
    "/app-screenshots/com.istack.sigature.app/4.jpg",
    "/app-screenshots/com.istack.sigature.app/5.jpg"
  ],
  "com.istack.artfonts": [
    "/app-screenshots/com.istack.artfonts/1.jpg",
    "/app-screenshots/com.istack.artfonts/2.jpg",
    "/app-screenshots/com.istack.artfonts/3.jpg",
    "/app-screenshots/com.istack.artfonts/4.jpg",
    "/app-screenshots/com.istack.artfonts/5.jpg"
  ],
  "com.istack.speakandtranslate": [
    "/app-screenshots/com.istack.speakandtranslate/1.jpg",
    "/app-screenshots/com.istack.speakandtranslate/2.jpg",
    "/app-screenshots/com.istack.speakandtranslate/3.jpg",
    "/app-screenshots/com.istack.speakandtranslate/4.jpg",
    "/app-screenshots/com.istack.speakandtranslate/5.jpg",
    "/app-screenshots/com.istack.speakandtranslate/6.jpg"
  ],
  "com.istack.home_workout": [
    "/app-screenshots/com.istack.home_workout/1.jpg",
    "/app-screenshots/com.istack.home_workout/2.jpg",
    "/app-screenshots/com.istack.home_workout/3.jpg",
    "/app-screenshots/com.istack.home_workout/4.jpg",
    "/app-screenshots/com.istack.home_workout/5.jpg"
  ],
  "com.istack.step_tracker": [
    "/app-screenshots/com.istack.step_tracker/1.jpg",
    "/app-screenshots/com.istack.step_tracker/2.jpg",
    "/app-screenshots/com.istack.step_tracker/3.jpg",
    "/app-screenshots/com.istack.step_tracker/4.jpg"
  ],
  "com.istack.wifi_speed_test": [
    "/app-screenshots/com.istack.wifi_speed_test/1.jpg",
    "/app-screenshots/com.istack.wifi_speed_test/2.jpg",
    "/app-screenshots/com.istack.wifi_speed_test/3.jpg",
    "/app-screenshots/com.istack.wifi_speed_test/4.jpg"
  ],
  "com.istack.nfc.wallet": [
    "/app-screenshots/com.istack.nfc.wallet/1.jpg",
    "/app-screenshots/com.istack.nfc.wallet/2.jpg",
    "/app-screenshots/com.istack.nfc.wallet/3.jpg",
    "/app-screenshots/com.istack.nfc.wallet/4.jpg",
    "/app-screenshots/com.istack.nfc.wallet/5.jpg",
    "/app-screenshots/com.istack.nfc.wallet/6.jpg"
  ],
  "com.istack.speaker_cleaner": [
    "/app-screenshots/com.istack.speaker_cleaner/1.jpg",
    "/app-screenshots/com.istack.speaker_cleaner/2.jpg",
    "/app-screenshots/com.istack.speaker_cleaner/3.jpg",
    "/app-screenshots/com.istack.speaker_cleaner/4.jpg",
    "/app-screenshots/com.istack.speaker_cleaner/5.jpg"
  ],
  "com.istack.guitar_tuner": [
    "/app-screenshots/com.istack.guitar_tuner/1.jpg",
    "/app-screenshots/com.istack.guitar_tuner/2.jpg",
    "/app-screenshots/com.istack.guitar_tuner/3.jpg",
    "/app-screenshots/com.istack.guitar_tuner/4.jpg",
    "/app-screenshots/com.istack.guitar_tuner/5.jpg"
  ],
  "com.istack.ar.meter": [
    "/app-screenshots/com.istack.ar.meter/1.jpg",
    "/app-screenshots/com.istack.ar.meter/2.jpg",
    "/app-screenshots/com.istack.ar.meter/3.jpg",
    "/app-screenshots/com.istack.ar.meter/4.jpg",
    "/app-screenshots/com.istack.ar.meter/5.jpg"
  ],
  "com.istack.phone_mirror": [
    "/app-screenshots/com.istack.phone_mirror/1.jpg",
    "/app-screenshots/com.istack.phone_mirror/2.jpg",
    "/app-screenshots/com.istack.phone_mirror/3.jpg",
    "/app-screenshots/com.istack.phone_mirror/4.jpg"
  ],
  "com.istack.color_identification": [
    "/app-screenshots/com.istack.color_identification/1.jpg",
    "/app-screenshots/com.istack.color_identification/2.jpg",
    "/app-screenshots/com.istack.color_identification/3.jpg",
    "/app-screenshots/com.istack.color_identification/4.jpg"
  ],
  "com.istack.speedometer": [
    "/app-screenshots/com.istack.speedometer/1.jpg",
    "/app-screenshots/com.istack.speedometer/2.jpg",
    "/app-screenshots/com.istack.speedometer/3.jpg",
    "/app-screenshots/com.istack.speedometer/4.jpg",
    "/app-screenshots/com.istack.speedometer/5.jpg"
  ],
  "com.istack.screen_mirroring": [
    "/app-screenshots/com.istack.screen_mirroring/1.jpg",
    "/app-screenshots/com.istack.screen_mirroring/2.jpg",
    "/app-screenshots/com.istack.screen_mirroring/3.jpg",
    "/app-screenshots/com.istack.screen_mirroring/4.jpg"
  ],
  "com.istack.hearing_from_distance": [
    "/app-screenshots/com.istack.hearing_from_distance/1.jpg",
    "/app-screenshots/com.istack.hearing_from_distance/2.jpg",
    "/app-screenshots/com.istack.hearing_from_distance/3.jpg",
    "/app-screenshots/com.istack.hearing_from_distance/4.jpg"
  ],
  "com.istack.compass.app": [
    "/app-screenshots/com.istack.compass.app/1.jpg",
    "/app-screenshots/com.istack.compass.app/2.jpg",
    "/app-screenshots/com.istack.compass.app/3.jpg",
    "/app-screenshots/com.istack.compass.app/4.jpg",
    "/app-screenshots/com.istack.compass.app/5.jpg"
  ],
  "com.istack.live.earth": [
    "/app-screenshots/com.istack.live.earth/1.jpg",
    "/app-screenshots/com.istack.live.earth/2.jpg",
    "/app-screenshots/com.istack.live.earth/3.jpg",
    "/app-screenshots/com.istack.live.earth/4.jpg",
    "/app-screenshots/com.istack.live.earth/5.jpg",
    "/app-screenshots/com.istack.live.earth/6.jpg"
  ],
  "com.istack.minimal_watch_faces": [
    "/app-screenshots/com.istack.minimal_watch_faces/1.jpg",
    "/app-screenshots/com.istack.minimal_watch_faces/2.jpg",
    "/app-screenshots/com.istack.minimal_watch_faces/3.jpg",
    "/app-screenshots/com.istack.minimal_watch_faces/4.jpg",
    "/app-screenshots/com.istack.minimal_watch_faces/5.jpg"
  ],
  "com.istack.funky_smiles": [
    "/app-screenshots/com.istack.funky_smiles/1.jpg",
    "/app-screenshots/com.istack.funky_smiles/2.jpg",
    "/app-screenshots/com.istack.funky_smiles/3.jpg",
    "/app-screenshots/com.istack.funky_smiles/4.jpg",
    "/app-screenshots/com.istack.funky_smiles/5.jpg"
  ],
  "com.istack.wallpaper_kawaii": [
    "/app-screenshots/com.istack.wallpaper_kawaii/1.jpg",
    "/app-screenshots/com.istack.wallpaper_kawaii/2.jpg",
    "/app-screenshots/com.istack.wallpaper_kawaii/3.jpg",
    "/app-screenshots/com.istack.wallpaper_kawaii/4.jpg"
  ],
  "com.istack.birthday_greetings": [
    "/app-screenshots/com.istack.birthday_greetings/1.jpg",
    "/app-screenshots/com.istack.birthday_greetings/2.jpg",
    "/app-screenshots/com.istack.birthday_greetings/3.jpg",
    "/app-screenshots/com.istack.birthday_greetings/4.jpg"
  ],
  "com.istack.wedding_invitation_maker": [
    "/app-screenshots/com.istack.wedding_invitation_maker/1.jpg",
    "/app-screenshots/com.istack.wedding_invitation_maker/2.jpg",
    "/app-screenshots/com.istack.wedding_invitation_maker/3.jpg",
    "/app-screenshots/com.istack.wedding_invitation_maker/4.jpg"
  ],
  "com.istack.smart_clock": [
    "/app-screenshots/com.istack.smart_clock/1.jpg",
    "/app-screenshots/com.istack.smart_clock/2.jpg",
    "/app-screenshots/com.istack.smart_clock/3.jpg",
    "/app-screenshots/com.istack.smart_clock/4.jpg"
  ],
  "com.istack.edge_lighting": [
    "/app-screenshots/com.istack.edge_lighting/1.jpg",
    "/app-screenshots/com.istack.edge_lighting/2.jpg",
    "/app-screenshots/com.istack.edge_lighting/3.jpg",
    "/app-screenshots/com.istack.edge_lighting/4.jpg",
    "/app-screenshots/com.istack.edge_lighting/5.jpg",
    "/app-screenshots/com.istack.edge_lighting/6.jpg"
  ],
  "com.istack.led_scroller": [
    "/app-screenshots/com.istack.led_scroller/1.jpg",
    "/app-screenshots/com.istack.led_scroller/2.jpg",
    "/app-screenshots/com.istack.led_scroller/3.jpg",
    "/app-screenshots/com.istack.led_scroller/4.jpg"
  ],
  "com.istack.house_design_plan_3d": [
    "/app-screenshots/com.istack.house_design_plan_3d/1.jpg",
    "/app-screenshots/com.istack.house_design_plan_3d/2.jpg",
    "/app-screenshots/com.istack.house_design_plan_3d/3.jpg",
    "/app-screenshots/com.istack.house_design_plan_3d/4.jpg",
    "/app-screenshots/com.istack.house_design_plan_3d/5.jpg"
  ],
  "ru.commands.voice.assistant": [
    "/app-screenshots/ru.commands.voice.assistant/1.png",
    "/app-screenshots/ru.commands.voice.assistant/2.png",
    "/app-screenshots/ru.commands.voice.assistant/3.png",
    "/app-screenshots/ru.commands.voice.assistant/4.png"
  ],
  "com.appx.bptracker": [
    "/app-screenshots/com.appx.bptracker/1.webp",
    "/app-screenshots/com.appx.bptracker/2.webp",
    "/app-screenshots/com.appx.bptracker/3.webp",
    "/app-screenshots/com.appx.bptracker/4.webp"
  ],
  "ios.appx.periodtracker": [
    "/app-screenshots/ios.appx.periodtracker/1.webp",
    "/app-screenshots/ios.appx.periodtracker/2.webp",
    "/app-screenshots/ios.appx.periodtracker/3.webp",
    "/app-screenshots/ios.appx.periodtracker/4.webp"
  ],
  "ios.appx.g1.ontario": [
    "/app-screenshots/ios.appx.g1.ontario/1.webp",
    "/app-screenshots/ios.appx.g1.ontario/2.webp",
    "/app-screenshots/ios.appx.g1.ontario/3.webp",
    "/app-screenshots/ios.appx.g1.ontario/4.webp"
  ],
  "ios.appx.electricianhandbook": [
    "/app-screenshots/ios.appx.electricianhandbook/1.webp",
    "/app-screenshots/ios.appx.electricianhandbook/2.webp",
    "/app-screenshots/ios.appx.electricianhandbook/3.webp",
    "/app-screenshots/ios.appx.electricianhandbook/4.webp"
  ],
  "ios.appx.lgvhgv": [
    "/app-screenshots/ios.appx.lgvhgv/1.webp",
    "/app-screenshots/ios.appx.lgvhgv/2.webp",
    "/app-screenshots/ios.appx.lgvhgv/3.webp",
    "/app-screenshots/ios.appx.lgvhgv/4.webp"
  ],
  "ios.appx.teleprompter": [
    "/app-screenshots/ios.appx.teleprompter/1.webp",
    "/app-screenshots/ios.appx.teleprompter/2.webp",
    "/app-screenshots/ios.appx.teleprompter/3.webp",
    "/app-screenshots/ios.appx.teleprompter/4.webp"
  ],
  "ios.appx.dmv.practice.test": [
    "/app-screenshots/ios.appx.dmv.practice.test/1.webp",
    "/app-screenshots/ios.appx.dmv.practice.test/2.webp",
    "/app-screenshots/ios.appx.dmv.practice.test/3.webp",
    "/app-screenshots/ios.appx.dmv.practice.test/4.webp"
  ],
  "ios.appx.sunglow.uv.index": [
    "/app-screenshots/ios.appx.sunglow.uv.index/1.webp",
    "/app-screenshots/ios.appx.sunglow.uv.index/2.webp",
    "/app-screenshots/ios.appx.sunglow.uv.index/3.webp",
    "/app-screenshots/ios.appx.sunglow.uv.index/4.webp",
    "/app-screenshots/ios.appx.sunglow.uv.index/5.webp",
    "/app-screenshots/ios.appx.sunglow.uv.index/6.webp"
  ],
  "ios.appx.tcg.card.value.scanner": [
    "/app-screenshots/ios.appx.tcg.card.value.scanner/1.webp",
    "/app-screenshots/ios.appx.tcg.card.value.scanner/2.webp",
    "/app-screenshots/ios.appx.tcg.card.value.scanner/3.webp"
  ],
  "ios.hair.color.changer.appx": [
    "/app-screenshots/ios.hair.color.changer.appx/1.webp",
    "/app-screenshots/ios.hair.color.changer.appx/2.webp",
    "/app-screenshots/ios.hair.color.changer.appx/3.webp"
  ],
  "ios.appx.math.solver.ai": [
    "/app-screenshots/ios.appx.math.solver.ai/1.webp",
    "/app-screenshots/ios.appx.math.solver.ai/2.webp",
    "/app-screenshots/ios.appx.math.solver.ai/3.webp",
    "/app-screenshots/ios.appx.math.solver.ai/4.webp"
  ],
  "ios.appx.nano.banana.image": [
    "/app-screenshots/ios.appx.nano.banana.image/1.webp",
    "/app-screenshots/ios.appx.nano.banana.image/2.webp",
    "/app-screenshots/ios.appx.nano.banana.image/3.webp",
    "/app-screenshots/ios.appx.nano.banana.image/4.webp",
    "/app-screenshots/ios.appx.nano.banana.image/5.webp",
    "/app-screenshots/ios.appx.nano.banana.image/6.webp"
  ],
  "ios.appx.background.remover": [
    "/app-screenshots/ios.appx.background.remover/1.webp",
    "/app-screenshots/ios.appx.background.remover/2.webp",
    "/app-screenshots/ios.appx.background.remover/3.webp",
    "/app-screenshots/ios.appx.background.remover/4.webp",
    "/app-screenshots/ios.appx.background.remover/5.webp",
    "/app-screenshots/ios.appx.background.remover/6.webp"
  ],
  "ios.appx.currency.converter": [
    "/app-screenshots/ios.appx.currency.converter/1.webp",
    "/app-screenshots/ios.appx.currency.converter/2.webp",
    "/app-screenshots/ios.appx.currency.converter/3.webp",
    "/app-screenshots/ios.appx.currency.converter/4.webp",
    "/app-screenshots/ios.appx.currency.converter/5.webp",
    "/app-screenshots/ios.appx.currency.converter/6.webp"
  ]
};
